// controllers/authController.ts
import { Request, Response } from "express";
// import { centralPrisma } from '../prisma-client/central-client';
import { getTenantPrisma } from "../prisma-client/tenant-client";
import { getCentralPrisma } from "../prisma-client/central-client";

import bcrypt from "bcryptjs";
import * as jwt from "jsonwebtoken";
import path from "path";
import dotenv from "dotenv";
import { generateToken } from "../utils/jwt";
import { sendEmail } from "../utils/email";
import { generateLoginEmailTemplate } from "../utils/templates/login-notification";

dotenv.config({ path: ".env" });

export async function masterLoginController(req: Request, res: Response) {
  const { email, password } = req.body;

  console.log("Master Data", email, password);

  try {
    const centralPrisma = getCentralPrisma();

    // 1. Fetch the Master Admin from Central DB
    const getMasterAdmin = await centralPrisma.superAdmin.findUnique({
      where: {
        email,
      },
    });

    console.log("Master Admin Found in MasterLofinController:", getMasterAdmin);

    if (!getMasterAdmin) {
      return res.status(404).json({ error: "Client admin not found" });
    }

    // 2. Validate password
    const isValid = await bcrypt.compare(password, getMasterAdmin.password!);
    if (!isValid) {
      return res.status(401).json({ error: "Invalid credentials" });
    }

    // 5. Generate JWT token via jwt helper
    const newToken = generateToken({
      id: getMasterAdmin.id,
      email: getMasterAdmin.email,
      role: getMasterAdmin.role,
    });

    console.log("Get New token Generated By Jwt.ts", newToken);

    // 5. Generate JWT token
    const token = jwt.sign(
      {
        id: getMasterAdmin.id,
        email: getMasterAdmin.email,
        role: getMasterAdmin.role,
      },
      process.env.JWT_SECRET!,
      { expiresIn: "30d" }
    );

    console.log("Get token Generated inside Auth Login", token);

    console.log("Login Successful", token);

    const emailHtml = generateLoginEmailTemplate(
      "John Doe",
      new Date().toLocaleString(),
      "192.168.0.1"
    );

    await sendEmail(getMasterAdmin.email, "Login Notification", emailHtml);

    // 6. Return success response with token
    return res.status(200).json({
      message: "Login successful",
      token: token,
      id: getMasterAdmin.id,
      email: getMasterAdmin.email,
      name: getMasterAdmin.name,
      role: getMasterAdmin.role,
    });
  } catch (error) {
    console.error("❌ Error in tenant login:", error);
    return res.status(500).json({ error: "Internal Server Error" });
  }
}
