// import { jsPDF } from 'jspdf';
// import { autoTable } from 'jspdf-autotable';

// declare module 'jspdf' {
//   interface jsPDF {
//     lastAutoTable?: {
//       finalY?: number;
//     };
//   }
// }

// export const singleDownloadReceipt = (item: any, log: any) => {
//   const doc = new jsPDF();

//   doc.setFontSize(16);
//   doc.text(`Payment Receipt - ${item?.student?.fullName}`, 14, 20);

//   const hiddenDetails = [
//     ['Student ID', item.student?.id],
//     ['Student Code', item.student?.studentCode],
//     ['Course', item.course?.name],
//     ['Total Amount', item.feeStructure?.totalAmount],
//     ['Amount Paid', item.amountPaid],
//     ['Amount Due', item.amountDue],
//     ['Payment Type', item.feeStructure?.paymentType],
//     ['Receipt No', item.receiptNo],
//     ['Payment Status', item.paymentStatus],
//   ];

//   autoTable(doc, {
//     startY: 30,
//     head: [['Field', 'Value']],
//     body: hiddenDetails,
//   });

//    // Single fee log table
//   autoTable(doc, {
//     startY: (doc.lastAutoTable?.finalY || 40) + 10,
//     head: [['#', 'Receipt No', 'Amount Paid', 'Mode', 'Date']],
//     body: [
//       [
//         1,
//         log.receiptNo || 'N/A',
//         log.amountPaid,
//         log.paymentMode,
//         log.paymentDate ? new Date(log.paymentDate).toISOString().split('T')[0] : 'N/A',
//       ]
//     ],
//   });

//   doc.save(`Receipt_${item?.student?.fullName || 'Student'}.pdf`);
// };

import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";

export const singleDownloadReceipt = (item: any, log: any) => {
  const doc = new jsPDF();

  // ===== HEADER =====
  doc.setFillColor(33, 150, 243); // Blue header
  doc.rect(0, 0, 210, 30, "F");

  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text("PAYMENT RECEIPT", 14, 18);

  doc.setFontSize(12);
  doc.text(`Student: ${item?.student?.fullName}`, 14, 26);

  doc.setTextColor(0, 0, 0);

  // ===== SECTION TITLE =====
  doc.setFontSize(14);
  doc.text("Student & Course Details", 14, 42);

  const hiddenDetails = [
    ["Student ID", item.student?.id],
    ["Student Code", item.student?.studentCode],
    ["Course", item.course?.name],
    ["Total Amount", item.feeStructure?.totalAmount],
    ["Amount Paid", item.amountPaid],
    ["Amount Due", item.amountDue],
    ["Payment Type", item.feeStructure?.paymentType],
    ["Receipt No", item.receiptNo],
    ["Payment Status", item.paymentStatus],
  ];

  // ===== BASE INFO TABLE =====
  autoTable(doc, {
    startY: 47,
    headStyles: {
      fillColor: [240, 240, 240],
      textColor: 0,
      fontStyle: "bold",
    },
    bodyStyles: { textColor: 40 },
    head: [["Field", "Value"]],
    body: hiddenDetails,
    theme: "grid",
  });

  // ===== FEE LOG SECTION =====
  doc.setFontSize(14);
  doc.text("Fee Log", 14, (doc.lastAutoTable?.finalY || 60) + 15);

  autoTable(doc, {
    startY: (doc.lastAutoTable?.finalY || 60) + 20,
    headStyles: {
      fillColor: [33, 150, 243],
      textColor: "#fff",
    },
    bodyStyles: {
      textColor: 40,
    },
    head: [["#", "Receipt No", "Amount Paid", "Mode", "Date"]],
    body: [
      [
        1,
        log.receiptNo || "N/A",
        log.amountPaid,
        log.paymentMode,
        log.paymentDate
          ? new Date(log.paymentDate).toISOString().split("T")[0]
          : "N/A",
      ],
    ],
    theme: "grid",
  });

  // ===== FOOTER =====
  const finalY = doc.lastAutoTable?.finalY || 250;

  doc.setFontSize(11);
  doc.text("Authorized Signature", 150, finalY + 20);
  doc.line(150, finalY + 22, 200, finalY + 22);

  doc.setFontSize(10);
  doc.text("Generated by Institute Management System", 14, finalY + 25);

  doc.save(`Receipt_${item?.student?.fullName || "Student"}.pdf`);
};
